name: hi365
description: Take care of you anytime, anywhere.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 0.0.20

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  dio: ^3.0.3
  bloc: ^2.0.0 #https://pub.dev/packages/bloc
  flutter_bloc: ^2.1.1 #https://pub.dev/packages/flutter_bloc
  equatable: ^0.6.1 #For bloc object comparable.
  flutter_secure_storage: ^3.3.1+1
  logger: ^0.7.0+2
  cron: ^0.2.2 #For schedule
  jaguar_jwt: ^2.1.6
  charts_flutter: ^0.8.1
  flutter_full_pdf_viewer: ^1.0.6
  scalable_image: ^1.1.2
  auto_size_text: 2.1.0
  device_info: 0.4.1+4 #This is for getting device information of Apple, android.
  package_info: 0.4.0+13 #This is for project version, like version in pubSpec.yaml
  flutter_widget_from_html_core: 0.2.4+4
  firebase_core: 0.4.3
  firebase_analytics: 5.0.9
  firebase_auth: 0.15.3
  google_sign_in: 4.0.0
  path_provider: 1.5.1
  apple_sign_in: ^0.1.0
  http: ^0.12.0+2
  url_launcher: 5.4.1
  encrypt: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/checkup/
    - assets/weather/
    - assets/dashboard/
    - assets/keyreport/
    - assets/launcher/
    - assets/reachUs/
    - assets/setting/
    - assets/images/
    - assets/images/qrcode.jpg
    - assets/images/barcode.gif
    - assets/images/checkup/img_nodata.png
    - assets/images/checkup/2.0x/img_nodata.png
    - assets/icons/cloud_download/cloud_download.png
    - assets/icons/cloud_download/2.0x/cloud_download.png
    - assets/icons/cloud_download/apple-logo.png
    - assets/images/ic_table_facetime.png
    - assets/images/healthbank/img_healthbook_download.png
    - assets/images/healthbank/img_progressbar.png
    - assets/images/healthbank/ic_notice.png
    - assets/images/healthbank/2.0x/ic_notice.png
    - assets/images/healthbank/ic_nv_next_orange.png
    - assets/images/healthbank/2.0x/ic_nv_next_orange.png
    - assets/images/healthbank/ic_table_next_grey.png
    - assets/images/healthbank/2.0x/ic_table_next_grey.png
    - assets/images/healthbank/ic_bankbook_m001_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m001_orange.png
    - assets/images/healthbank/ic_bankbook_m002_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m002_orange.png
    - assets/images/healthbank/ic_bankbook_m003_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m003_orange.png
    - assets/images/healthbank/ic_bankbook_m004_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m004_orange.png
    - assets/images/healthbank/ic_bankbook_m005_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m005_orange.png
    - assets/images/healthbank/ic_bankbook_m006_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m006_orange.png
    - assets/images/healthbank/ic_bankbook_m008_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m008_orange.png
    - assets/images/healthbank/ic_bankbook_m009_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m009_orange.png
    - assets/images/healthbank/ic_bankbook_m010_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m010_orange.png
    - assets/images/healthbank/ic_bankbook_m011_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m011_orange.png
    - assets/images/healthbank/ic_bankbook_m012_orange.png
    - assets/images/healthbank/2.0x/ic_bankbook_m012_orange.png
    - assets/images/healthbank/ic_toast_download.png
    - assets/images/healthbank/2.0x/ic_toast_download.png
    - assets/images/healthbank/ic_nv_download_orange.png
    - assets/images/healthbank/2.0x/ic_nv_download_orange.png
    - assets/pdf/hrb_app_healthbook_auth.pdf
    - assets/pdf/hrb_app_healthbook_download.pdf
    - assets/splash/splash.png
